###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: ies-la-cierva-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=admin1234
        - MYSQL_DATABASE=testdb
        - MYSQL_USER=testuser
        - MYSQL_PASSWORD=admin1234
      ports:
        - "9202:3306"

    webserver:
      image: nginx:alpine
      container_name: ies-la-cierva-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9200:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: ies-la-cierva-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

